### sign up
POST http://localhost:8000/account/signup
Content-Type: application/json

{
    "username": "beerus7",
    "password": "123456",
    "repassword": "123456",
    "name": "long7",
    "server": "3"
}

### login
POST http://localhost:8000/account/login
Content-Type: application/json

{
    "username": "beerus7",
    "password": "123456",
    "server": "3"
}