### get all
GET http://localhost:8000/product/all
Content-Type: application/json

{
    "server": "2"
}

### get one
GET http://localhost:8000/product/one/2002

### insert new product
POST http://localhost:8000/product/create_new
Content-Type: application/json

{
    "name":"product 2",
    "price":"1200000",
    "image":"product 2",
    "server": "3"
}

